site_name: tomrade 
nav:
    - Home: index.md
    - Projects: projects.md
    - Useful Links: links.md
theme:
    name: material
    palette:
        scheme: slate
        primary: white
        accent: deep orange