site_name: tomrade 
nav:
    - Home: index.md
    - Projects: projects.md
    - Useful Links: links.md
theme:
    logo: img/logo.png
    name: material
    palette:
        scheme: slate
        primary: blue grey
        accent: deep orange