site_name: tomrade 
nav:
    - Home: 
        - About: index.md
    - Projects:
        - Security : projects.md
    - Notes:
        - Windows:
            - Event Logs:
                - Basics: event_logs.md
                - WELM usage: welm.md
            - HyperV: hyperv.md
            - iis: iis.md
    - Random Stuff:
        - Useful Links: links.md
theme:
    logo: img/logo.png
    name: material
    features:
        - navigation.tabs
    palette:
        scheme: slate
        primary: indigo
        accent: deep orange
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences