site_name: tomrade 
nav:
    - Home: 
        - About: index.md
    - Projects:
        - Security : projects.md
    - Useful Links: links.md
theme:
    logo: img/logo.png
    name: material
    features:
        - navigation.tabs
    palette:
        scheme: slate
        primary: blue grey
        accent: deep orange